[package]
name = "rtfm"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
tui = "0.19.0"
crossterm = "0.27.0"
anyhow = "1.0.75"
tokio = { version = "1.0", features = ["full"] }
regex = "1.10.2"
